### PR TITLE
Fix errors in participant add search

### LINKED ISSUE #4784: Fix "search" in participant "New participant"
**Describe the bug**
The search masks has problems if you navigate back and forward

**How to Reproduce**
In the add participant add mask: 
1. Have two users (A and B)
2. search A in username
3. Select A
4. Press Previous 
5. This snackbar Error is thrown: ```Error: data.search[0].member_number must be string```
6. Press Previous
7. remove A's data and add B's data
8. Press Next
9. This snackbar Error is thrown: ```Error: data.search[0].member_number must be string```
10. And only A is selectable in step 2

You can navigate between prev/next and the error will reappear every time you go from step 1 to ste p2

**Expected behavior**

- [ ] The Error should not be thrown 
- [ ] B should be selectable in Nr. 10

### PR DESCRIPTION
**Pull request by anbebe**
Closes #4784

### CODE REVIEW

File: client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/components/participant-create-wizard/participant-create-wizard.component.ts [hunk 1]
```diff
@@ -349,7 +356,11 @@ export class ParticipantCreateWizardComponent extends BaseMeetingComponent imple
     }
 
     private checkSelectedGroupsCanManage(): boolean {
-        return (this.detailView.personalInfoForm.get(`group_ids`).value ?? [])
+        const group_ids =
+            this.detailView.personalInfoForm.get(`group_ids`).value?.length > 0
+                ? this.detailView.personalInfoForm.get(`group_ids`).value
+                : [];
```
Comment (bastianjoel) [inline client/src/app/site/pages/meetings/pages/participants/pages/participant-detail/pages/participant-detail-manage/components/participant-create-wizard/participant-create-wizard.component.ts:362]:
```suggestion
        const group_ids = this.detailView.personalInfoForm.get(`group_ids`).value ?? [];
```

**Review by bastianjoel — CHANGES_REQUESTED** [review]

**Review by bspekker — APPROVED** [review]

**Review by bastianjoel — APPROVED** [review]
