### PR TITLE
fix set presence via participant number status

### LINKED ISSUE #1972: Set presence via participant number is wrong
Reproduction:
* Give a particiapant a participant number
* Enable the "Enable participant presence view" setting in Participants
* In participant list use three-dot-menu "Presence"
* Enter the participant number
* Click "Change presence"

The presence status shown on this page is the opposite of the status in the participant list.

### PR DESCRIPTION
**Pull request by bastianjoel**
resolves #1972

### CODE REVIEW

**Review by luisa-beerboom — APPROVED** [review]

File: client/src/app/site/pages/meetings/pages/participants/pages/participant-presence/components/participant-presence/participant-presence.component.ts [hunk 1]
```diff
@@ -48,6 +49,7 @@ export class ParticipantPresenceComponent implements OnInit {
         try {
             this.errorMsg = null;
             this.lastChangedUser = this.userRepo.getViewModelByNumber(number)!;
+            this.lastChangedUserPresent = !this.lastChangedUser?.isPresentInMeeting();
             await this.userRepo.togglePresenceByNumber(number);
```
Comment (jsangmeister) [inline client/src/app/site/pages/meetings/pages/participants/pages/participant-presence/components/participant-presence/participant-presence.component.ts:53]: Can't you just use the user observable instead of fetching the `ViewUser` and calculate the value based on that? I think I would like that more than an extra variable.

**Review by jsangmeister — CHANGES_REQUESTED** [review]

**Review by emanuelschuetze — APPROVED** [review]

File: client/src/app/site/pages/meetings/pages/participants/pages/participant-presence/components/participant-presence/participant-presence.component.ts (hunk 1 above)
Comment (bastianjoel) [reply client/src/app/site/pages/meetings/pages/participants/pages/participant-presence/components/participant-presence/participant-presence.component.ts:53]: I thought about that too but since this is a alert I think it might be better if the content does not change if the presence status gets changed from somewhere else.

Comment (jsangmeister) [reply client/src/app/site/pages/meetings/pages/participants/pages/participant-presence/components/participant-presence/participant-presence.component.ts:53]: Ok, I see that. Then, I would remove the `lastChangedUser` variable since it does not seem to be used anywhere else and check for `lastChangedUserPresent === null` to see if the message should be displayed or not.

Comment (bastianjoel) [reply client/src/app/site/pages/meetings/pages/participants/pages/participant-presence/components/participant-presence/participant-presence.component.ts:53]: The property `lastChangedUser` is used within the template to display the `full_name`.

Comment (jsangmeister) [reply client/src/app/site/pages/meetings/pages/participants/pages/participant-presence/components/participant-presence/participant-presence.component.ts:53]: ok

**Review by jsangmeister — APPROVED** [review]

**Comment by alveolus** [comment]
Erfassung der Anwesenheit über die Teilnehmendennummer funktioniert wieder korrekt
