### PR TITLE
Fix different issues around vote

### LINKED ISSUE #4785: Fix vote
**Describe the bug**
Several things are wrong/missing with the vote

**How to Reproduce**
1. Navigate to an election
2. Put at least two candidates on the election list
3. Create an election with Y/N per candidate 
4. Start the election
5. sth visually should change (more in Expected behaviour)
6. Try to give more than one vote -> you are prevented to give more than one vote 
7. Create a different election with Y/N/A per candidate
8. If you send your vote then the dialog does not close after the first time 
9. In general the dialog shows the wrong wording

**Expected behavior**
Image

- [x]  If Available votes is >1 is should be presented
- [x] The Y/N per candidate should also have the "Minimum amount of votes" and "Maximum amount of votes"
- [x] The text for the "Submit selection now?" should again show how many of how many votes you are sending 
- [x] The dialog should not open two times

**Additional context**

### PR DESCRIPTION
**Pull request by Elblinator**
closes #4785

### CODE REVIEW

**Review by rrenkert — APPROVED** [review]

File: client/src/app/site/pages/meetings/modules/poll/components/base-poll-form/base-poll-form.component.ts [hunk 1]
```diff
@@ -300,9 +304,7 @@ export abstract class BasePollFormComponent extends BaseComponent implements OnI
     public showMinMaxVotes(data: any): boolean {
         const selectedPollMethod: FormPollMethod = this.pollMethodControl.value;
         return (
-            (selectedPollMethod === `Y` ||
-                selectedPollMethod === `N` ||
-                (selectedPollMethod === `YNA` && this.allowToSetMinMaxOnYNA)) &&
+            (selectedPollMethod === `Y` || (selectedPollMethod !== `yna` && this.allowToSetMinMax)) &&
```
Comment (bastianjoel) [inline client/src/app/site/pages/meetings/modules/poll/components/base-poll-form/base-poll-form.component.ts:307]:
```suggestion
            (selectedPollMethod === `Y` || (selectedPollMethod !== `YNA` && this.allowToSetMinMax)) &&
```

Should be uppercase ig?

**Review by bastianjoel — CHANGES_REQUESTED** [review]

File: client/src/app/site/pages/meetings/modules/poll/components/base-poll-form/base-poll-form.component.ts (hunk 1 above)
Comment (Elblinator) [reply client/src/app/site/pages/meetings/modules/poll/components/base-poll-form/base-poll-form.component.ts:307]: no yna in lower case is the list option

Comment (bastianjoel) [reply client/src/app/site/pages/meetings/modules/poll/components/base-poll-form/base-poll-form.component.ts:307]: Please at least use the enum from `FormPollMethod` to prevent further confusion in the future.

**Review by anbebe — APPROVED** [review]
For what reason do we have two enums that are almost identical? (PollMethod and FormPollMethod) Can it be reduced to one? @Elblinator opens a new issue for that topic.
