### PR TITLE
fix history mode

### LINKED ISSUE #1648: History mode some not existing data still present
Some data that wasn't available at a certain history entry is still displayed in history mode. 

This can for example be reproduced by the following steps:

- Create motion
- Create new vote inside that motion 
- Open history page for that motion
- Choose the Motion created timestamp
- You can still see the vote in that motion

### PR DESCRIPTION
**Pull request by bastianjoel**
resolves #1648

Also adds the timestamp of the current history position to the header and tests.

### CODE REVIEW

**Review by emanuelschuetze — APPROVED** [review]

File: client/src/app/site/pages/meetings/pages/history/components/history-banner/history-banner.component.ts [hunk 1]
```diff
@@ -10,6 +11,14 @@ import { HistoryService } from '../../services/history.service';
 export class HistoryBannerComponent {
     public constructor(private historyService: HistoryService) {}
 
+    public get historyPositionTimestamp(): string {
+        if (!this.historyService.currentHistoryPosition?.timestamp) {
+            return ``;
+        }
+
+        return unix(this.historyService.currentHistoryPosition.timestamp).local().format(`lll`);
```
Comment (luisa-beerboom) [inline client/src/app/site/pages/meetings/pages/history/components/history-banner/history-banner.component.ts:19]: Instead of doing this, use a pipe in the template. You'll need to import the `PipesModule` in the `module.ts`.

**Review by luisa-beerboom — CHANGES_REQUESTED** [review]

**Review by luisa-beerboom — APPROVED** [review]
