### PR TITLE
Fix motion favorite icon for public access users

### LINKED ISSUE #4331: Hide motion favorite icon for public access
**Current behavior**
If motions are visible for public access the star icon in the upper right of a motion detail view is visible and clickable. As a not logged in user the error message 

`Error: Anonymous is not allowed to execute personal_note.create`

appears.

Reproduction:

* Have a meeting with at least one motion
* Make the meeting available via public access
* Allow the public group to see motions
* Navigate to the motion detail view as public access user
* Click the star icon in the upper right.

**Wanted behavior**
In public access mode the icon should not be available.

**Additional context**

### PR DESCRIPTION
**Pull request by anbebe**
Closes #4331

### CODE REVIEW

File: client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-manage-title/motion-manage-title.component.ts [hunk 1]
```diff
@@ -36,6 +36,9 @@ export class MotionManageTitleComponent extends BaseMotionDetailChildComponent {
 
     private _changeRecoMode: ChangeRecoMode;
 
+    @Input()
+    public anonymUser: boolean;
```
Comment (bastianjoel) [inline client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-manage-title/motion-manage-title.component.ts:40]: The naming of for example `isAnonymous` is outdated at some places. The feature was renamed and therefore the properties should be too. 

```suggestion
    public publicAccess: boolean;
```

File: client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-manage-title/motion-manage-title.component.ts [hunk 2]
```diff
@@ -36,6 +36,9 @@ export class MotionManageTitleComponent extends BaseMotionDetailChildComponent {
...
+
```
Comment (bastianjoel) [inline client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-manage-title/motion-manage-title.component.ts:41]: Move above `updateCrMode`.

**Review by bastianjoel — APPROVED** [review]

**Review by Elblinator — APPROVED** [review]
