### PR TITLE
Fix approximation for pdf scrolling

### LINKED ISSUE #4710: Fix PDF Scroll behaviour
**Describe the bug**
The PDF scroll via the prjector is not scrolling via the correct dimentions.

**How to Reproduce**
1. Create a pdf with several pages
2. Project the PDF
3. Create projector
4. Change the format of the projector to 210:297 (Thats DinA 4 format)
5. Scroll down (by approximately projector height)
6. the Pages jump too much down

**Expected behavior**
That the pages jump more to the actuele height of the projector

**Additional context:**
This feature was introdyuced here:
https://github.com/OpenSlides/openslides-client/pull/4628

### PR DESCRIPTION
**Pull request by anbebe**
Closes #4710 

Improves the approximation for pdf scrolling, especially for only scrolling in one direction, but is still an approximation.

### CODE REVIEW

**Comment by rrenkert** [comment]
> The approximation is incorrect for most PDFs I used to test thsi PR. Instead of an approximation can't you just use pdfjs to get the page height of the pdf in the view?

As of the definition in the issue the current implementation is ok for now.

File: client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/projector-detail/projector-detail.component.ts [hunk 1]
```diff
@@ -109,6 +109,18 @@ export class ProjectorDetailComponent extends BaseMeetingComponent implements On
...
 
+    /** stores the decimal places that could not be scrolled
+     *  at once for the projector height */
+    public get summedOverflowSteps(): number {
+        return this._summedOverflowSteps;
+    }
+
+    public set summedOverflowSteps(value: number) {
+        this._summedOverflowSteps = value;
+    }
```
Comment (luisa-beerboom) [inline client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/projector-detail/projector-detail.component.ts:120]: No real need to write getters, if you're only going to use the property class-internally. Just read the private property as-is.

File: client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/projector-detail/projector-detail.component.ts [hunk 2]
```diff
@@ -368,4 +381,22 @@ export class ProjectorDetailComponent extends BaseMeetingComponent implements On
...
         );
     }
+
+    public scrollPDFPage(direction: ScrollScaleDirection): void {
+        if (this.projector.scroll <= 0) {
+            this.summedOverflowSteps = 0;
+        }
+        direction === ScrollScaleDirection.Up
+            ? (this.summedOverflowSteps += this.projector.height / 100 - Math.floor(this.projector.height / 100))
+            : (this.summedOverflowSteps -= this.projector.height / 100 - Math.floor(this.projector.height / 100));
```
Comment (luisa-beerboom) [inline client/src/app/site/pages/meetings/pages/projectors/modules/projector-detail/components/projector-detail/projector-detail.component.ts:391]:
```suggestion
        this._summedOverflowSteps += (this.projector.height % 100) / 100 * (direction === ScrollScaleDirection.Up ? 1 : -1);
```
I believe this would be equivalent.

**Review by luisa-beerboom — CHANGES_REQUESTED** [review]

**Review by luisa-beerboom — APPROVED** [review]
