### PR TITLE
Fixes the resetting of user passwords

### LINKED ISSUE #331: Reset password sends a request to the wrong url
From `/login/reset-password`, the client will sind a post request to `environment.urlPrefix + '/users/reset-password/'` which does not exist anymore

### PR DESCRIPTION
**Pull request by GabrielInTheWorld**
Fixes #331

### CODE REVIEW

File: client/src/app/site/login/components/reset-password-confirm/reset-password-confirm.component.ts [hunk 1]
```diff
@@ -69,7 +70,7 @@ export class ResetPasswordConfirmComponent extends BaseComponent implements OnIn
                         this.router.navigate([`..`]);
                     });
                 } else {
-                    this.user_id = params.user_id;
+                    this.user_id = parseInt(params.user_id, 10);
```
Comment (tsiegleauq) [inline client/src/app/site/login/components/reset-password-confirm/reset-password-confirm.component.ts:73]: `Number(params.user_id)`

File: client/src/app/app-routing.module.ts [hunk 2]
```diff
@@ -18,8 +18,8 @@ const routes: Route[] = [
         component: LoginWrapperComponent,
         children: [
             { path: ``, component: LoginMaskComponent, pathMatch: `full` },
-            { path: `reset-password`, component: ResetPasswordComponent },
-            { path: `reset-password-confirm`, component: ResetPasswordConfirmComponent },
+            { path: `forget-password`, component: ResetPasswordComponent },
+            { path: `forget-password-confirm`, component: ResetPasswordConfirmComponent },
```
Comment (tsiegleauq) [inline client/src/app/app-routing.module.ts:22]: micro opt: but both components for resetting and forgetting a passwort could be an own module, since it's rare that a user will need it and having an own module would allow to lazy load these modules

**Review by tsiegleauq — CHANGES_REQUESTED** [review]

**Review by emanuelschuetze — APPROVED** [review]

**Comment by emanuelschuetze** [comment]
@tsiegleauq you can review later
