### PR TITLE
disable tinymce blockquoute

### LINKED ISSUE #2135: Motion text editor: justification of text format didn't work
Description: Editing a text segment or the whole text of a motion in justification format doesn't work. The editing in the text editor works fine, but it isn't saved. The motion is still in the original text format. 

Text editor: text format changed to justify
Screenshot_20230328_163113

Motion view after save
Screenshot_20230328_163139

Reproduction:
1. create a motion with at least 3-4 lines.
2. edit the text format to justification and save it

What should happen:
Text format can be changed to justification (justify).

### PR DESCRIPTION
**Pull request by bastianjoel**
resolves #2135

### CODE REVIEW

File: client/src/app/ui/modules/editor/components/editor/editor.component.ts [hunk 1]
```diff
@@ -36,6 +37,48 @@ export class EditorComponent extends BaseFormControlComponent<string> implements
...
+                    { title: _(`Pre`), format: `pre` }
+                ]
+            },
+            {
+                title: _(`Alignment`),
+                items: [
+                    { title: _(`Left`), format: `alignleft` },
+                    { title: _(`Center`), format: `aligncenter` },
+                    { title: _(`Right`), format: `alignright` },
+                    { title: _(`Justify`), format: `alignjustify` }
```
Comment (luisa-beerboom) [inline client/src/app/ui/modules/editor/components/editor/editor.component.ts:78]: Haven't looked too deeply into how this works with tinyMCE, but shouldn't the `alignjustify` item be removed if you want to remove the option?

**Review by luisa-beerboom — COMMENTED** [review]
Aside from the more specific comment:
As far as I see, this implements blanket changes on the entire editor.
Wouldn't this cause the other places where we use the editor component to also not have blockquote?
Do we want to disable blockquote everywhere or only in places where it may interfere with pdf generation?

**Review by luisa-beerboom — APPROVED** [review]

**Review by rrenkert — APPROVED** [review]
