### PR TITLE
Fixes routing problem

### LINKED ISSUE #244: Routing to list of speakers via agenda is broken
Clicking on the speaker icon in one entry of the agenda list, I'm navigated to the dashboard. Also the link to the LOS from the 3-dot menu of an agenda item does not work

### LINKED ISSUE #245: Routing from agenda item to assignment is broken
Maybe related to https://github.com/OpenSlides/openslides-client/issues/244

Clicking on an assignment in the agenda item list, I'm redirected to the dashboard

### LINKED ISSUE #247: Routing on voting banner is broken
When clicking on the voting banner, I'm navigated to the dashboard.

### LINKED ISSUE #248: Routing to upload component is broken
I'm navigated to the dashboard.

### LINKED ISSUE #250: Routing needs to be fixed: Collecting all places
- #248 
- #247 
- #245 
- #244 
- New-amendment button in the bottom right corner of the motion detail view.

### PR DESCRIPTION
**Pull request by GabrielInTheWorld**
Fixes #244 
Fixes #245 
Fixes #247 
Fixes #248 
Fixes #250 

I have gone through every component, that uses any kind of `routerLink` or `router.navigate` or `router.navigateByUrl` and check, if routing will be successful.

### CODE REVIEW

File: client/src/app/site/cinema/components/cinema/cinema.component.ts [hunk 1]
```diff
@@ -68,7 +68,7 @@ export class CinemaComponent extends BaseComponent implements OnInit {
     public get projectorUrl(): string {
         if (this.projector) {
             if (this.operator.hasPerms(this.permission.projectorCanManage)) {
-                return `/projectors/detail/${this.projector.id}`;
+                return `/${this.activeMeetingId}/projectors/detail/${this.projector.id}`;
             } else {
                 return `/projector/${this.projector.id}`;
```
Comment (tsiegleauq) [inline client/src/app/site/cinema/components/cinema/cinema.component.ts:73]: I suppose this will require adjustment aswell?

**Review by tsiegleauq — CHANGES_REQUESTED** [review]
missing:
- [x] ageda -> tags
- [ ] fullscreen projector links to `https://localhost:8000/projector/{{id}}` (in projector detail hit projector again)
- [ ] deleting current folder links be to "8000/1/mediafiles/1" - apparently the base folder for mediafiles is "8000/1/mediafiles/mediafiles". Not entirely sure what is the deeper meaning of this. We either remove the double use ("mediafiles/mediafiles") or specially link "mediafiles" to "mediafiles/mediafiles" after deletion. (can be done seperately)

besides that, everything was working fine. Resolve and merge after

**Comment by GabrielInTheWorld** [comment]
> * [ ]  fullscreen projector links to `https://localhost:8000/projector/{{id}}` (in projector detail hit projector again)

As I know, the fullscreen projector is not meeting-related and therefore the routing to `https://localhost:8000/projector/{{id}}` is intended. 

> * [ ]  deleting current folder links be to "8000/1/mediafiles/1" - apparently the base folder for mediafiles is "8000/1/mediafiles/mediafiles". Not entirely sure what is the deeper meaning of this. We either remove the double use ("mediafiles/mediafiles") or specially link "mediafiles" to "mediafiles/mediafiles" after deletion. (can be done seperately)

I will implement, that one will be redirected to the folder's parent-directory.
