### PR TITLE
Fixed topic poll chart colors

### LINKED ISSUE #1729: poll (survey) results display only one false color
**Description:** Polls (survey) results display only one color instead of the other colors given by the options available. The image has three options to choose from. And not a single color is correclty displayed. Only the chart value is correct. 

Screenshot_20221024_115135

**Reproduction:**
Important: Two accounts needed; admin and for example delegate
1. open a meeting as admin
2. open agenda
3. create a new agenda item and open it.
4. create a new poll. Choose Admin and delegates as Entitles to cote. Add at least three options to choose from and save it.
5. Start the poll and choose Option a as Admin
6. Open the meeting as Delegate in another browser and vote option b or c
7. open the other browser as admin again and stop the poll. publish it.
8. The colors should not be correctly displayed.

**Expected behavior:** The colors in the chart result should be correctly displayed according the colors given by the options.

### PR DESCRIPTION
**Pull request by luisa-beerboom**
Closes #1729

### CODE REVIEW

File: client/src/app/site/pages/meetings/modules/poll/components/chart/chart.component.ts [hunk 1]
```diff
@@ -157,7 +157,12 @@ export class ChartComponent {
                 // removes undefined and null values
                 return chartDate.data.filter(data => !!data);
             });
-            if (!this.circleColors || inputChartData.length !== this.circleColors[0].backgroundColor.length) {
+            if (
+                !this.circleColors ||
+                ![inputChartData.length, inputChartData[0].data.length].includes(
+                    this.circleColors[0].backgroundColor.length
+                )
```
Comment (bastianjoel) [inline client/src/app/site/pages/meetings/modules/poll/components/chart/chart.component.ts:164]: I think this should be
```suggestion
                ![this.circleColors[0].backgroundColor.length, this.circleColors[0].hoverBackgroundColor.length].includes(
                    inputChartData.length
                )
```

**Review by bastianjoel — CHANGES_REQUESTED** [review]

**Review by bastianjoel — APPROVED** [review]

**Review by rrenkert — APPROVED** [review]
