### PR TITLE
Hide group/external_id for non meeting admins

### LINKED ISSUE #4155: Fix `group.create` for not admins
**Current behaviour:**
If a user is not in the admin group then this user cannot create new groups

**Repo:**
1. create a group and activate every permission
2. assign a user this group and only this group
3. login as this user
4. try creating a new group
5. ```Error: Missing permission: Not admin of this meeting```

Payload:
```
[
  {
    "action": "group.create",
    "data": [
      {
        "meeting_id": 1,
        "name": "werw",
        "external_id": ""
      }
    ]
  }
]
```

Response:
```
{"success": false, "message": "Missing permission: Not admin of this meeting"}
```

**Wanted behaviour:**
If a participant has the permission user.canManage (in that meeting) then this user should be able to create a new group

### PR DESCRIPTION
**Pull request by reiterl**
Resolve #4155

### CODE REVIEW

**Review by bastianjoel — APPROVED** [review]

File: client/src/app/site/pages/meetings/pages/participants/modules/groups/components/group-list/group-list.component.ts [hunk 1]
```diff
@@ -277,4 +284,11 @@ export class GroupListComponent extends BaseMeetingComponent implements OnInit,
         }
         return true;
     }
+
+    /**
+     * Function to allow to edit the external_id
+     */
+    public get allowExternalId(): boolean {
+        return this.operator.isMeetingAdmin || this.operator.isAccountAdmin;
+    }
```
Comment (Elblinator) [inline client/src/app/site/pages/meetings/pages/participants/modules/groups/components/group-list/group-list.component.ts:293]: Account admins are not allowed to update the external ID, please remove them

**Review by Elblinator — CHANGES_REQUESTED** [review]

File: client/src/app/site/pages/meetings/pages/participants/modules/groups/components/group-list/group-list.component.ts (hunk 1 above)
Comment (reiterl) [reply client/src/app/site/pages/meetings/pages/participants/modules/groups/components/group-list/group-list.component.ts:293]: Are orga admins or superadmins allowed to update the external Id?

**Review by bastianjoel — APPROVED** [review]

**Review by Elblinator — APPROVED** [review]
