### PR TITLE
Fix motion default workflow selection

### LINKED ISSUE #3319: Motion creation: default workflow not displayed
**Description:** During motion creation the default workflow is not shown/preselected. 

image

**Reproduction:**
1. Open a meeting
2. open Motions > create a motion > Check workflow box. It is empty. 

**What should happen:** 
During motion creation the workflow box should not be empty. There is always a workflow set-up which should be preselected.

### PR DESCRIPTION
**Pull request by bastianjoel**
resolves #3319

### CODE REVIEW

File: client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-content/motion-content.component.ts [hunk 1]
```diff
@@ -488,7 +488,7 @@ export class MotionContentComponent extends BaseMotionDetailChildComponent {
             agenda_parent_id: [],
             submitter_ids: [[]],
             supporter_user_ids: [[]],
-            workflow_id: [],
+            workflow_id: [+this.meetingSettingService.instant(`motions_default_workflow_id`)],
```
Comment (jsangmeister) [inline client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-content/motion-content.component.ts:491]: If this form is also used for amendments, you may have to use `motions_default_amendment_workflow_id`

Comment (bastianjoel) [reply client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-content/motion-content.component.ts:491]: `AmendmentCreateWizardComponent` is used to create amendments.

Comment (jsangmeister) [reply client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-content/motion-content.component.ts:491]: ok, because in line 484 above this, it is checked whether this is a paragraph bsaed amendment, that's where my thought came from. Is this check unnecessary then?

Comment (bastianjoel) [reply client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-content/motion-content.component.ts:491]: The component is also used for editing motions. But in that case a workflow is already set.

Comment (jsangmeister) [reply client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-content/motion-content.component.ts:491]: ok!

**Review by luisa-beerboom — APPROVED** [review]

**Review by rrenkert — APPROVED** [review]
