### PR TITLE
Fix save button in Settings

### LINKED ISSUE #5170: Fix activated save button in meeting > settings > LoS
**Describe the bug**
If the settings are saved (under specific circumstances) then the save button stays active and to be deactivated needs to be pressed twice

**How to Reproduce**
1. navigate to meeting > settings > List of Speakers 
2. Enable point of orders
3. enable Enable specifications and ranking for possible motions
4. create a new entry
5. save
6. deavtivate "Enable point of orders"
7. save
8. activate  "Enable point of orders"
9. what you will see is that the save button stays active

**Expected behavior**
the save button should be deactivated after being pressed once

### PR DESCRIPTION
**Pull request by Elblinator**
closes #5170

### CODE REVIEW

File: client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail/meeting-settings-group-detail.component.ts [hunk 1]
```diff
@@ -126,8 +135,8 @@ export class MeetingSettingsGroupDetailComponent
      * Saves every field in this config-group.
      */
     public async saveAll(): Promise<void> {
-        this.cd.detach();
```
Comment (bastianjoel) [inline client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail/meeting-settings-group-detail.component.ts:129]: Why move this?

Also might be a good idea to move `reattach` into finally.

**Review by bastianjoel — CHANGES_REQUESTED** [review]

**Review by bastianjoel — APPROVED** [review]

File: client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail/meeting-settings-group-detail.component.ts [hunk 2]
```diff
@@ -167,13 +176,17 @@ export class MeetingSettingsGroupDetailComponent
             if (Object.keys(data).length) {
                 await this.repo.update(data, { meeting: this.meeting });
             }
+            for (const key in data) {
+                this.originalSettings[key] = data[key];
+            }
```
Comment (bastianjoel) [inline client/src/app/site/pages/meetings/pages/meeting-settings/pages/meeting-settings-group-detail/components/meeting-settings-group-detail/meeting-settings-group-detail.component.ts:181]: No. 
Add `markForCheck` here: https://github.com/OpenSlides/openslides-client/pull/5356/files#diff-76c1dd8fdaed41f88df4e5801b1790e31f95e50dc41c7e3a6995aefa80e4f642R114

**Review by bastianjoel — APPROVED** [review]

**Comment by bastianjoel** [comment]
There are linter errors

**Review by MSoeb — APPROVED** [review]
works as intened
