### PR TITLE
Add filter for gender in participant list and fix duplicated group ids in multiselect

### LINKED ISSUE #2814: Add filter for gender in participant list
The participant list should be filterable by gender.

### PR DESCRIPTION
**Pull request by rrenkert**
closes #2814

### CODE REVIEW

**Review by emanuelschuetze — APPROVED** [review]

**Comment by emanuelschuetze** [comment]
@rrenkert feel free to merge this PR or split out in separate PR.

File: client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.ts [hunk 1]
```diff
@@ -269,7 +269,9 @@ export class ParticipantListComponent extends BaseMeetingListViewComponent<ViewU
                         const nextGroupIds = user.group_ids().filter(id => this.activeMeeting.default_group_id !== id);
                         return {
                             id: user.id,
-                            group_ids: nextGroupIds.concat(chosenGroupIds)
+                            group_ids: nextGroupIds
+                                .concat(chosenGroupIds)
+                                .filter((v, i, a) => a.findIndex(v2 => v2 === v) === i)
```
Comment (luisa-beerboom) [inline client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.ts:274]: What's this supposed to do?

Comment (luisa-beerboom) [reply client/src/app/site/pages/meetings/pages/participants/pages/participant-list/components/participant-list/participant-list.component.ts:274]:
```suggestion
                            group_ids: [...new Set(nextGroupIds.concat(chosenGroupIds))]
```

**Review by luisa-beerboom — CHANGES_REQUESTED** [review]

**Review by luisa-beerboom — APPROVED** [review]
