### PR TITLE
Fix a problem with update of presence in account-button

### LINKED ISSUE #4251: User Profile: Presence status can't be set by participants
**Describe the bug**
Currently it is not possible to change the presence status via user profile. Users can't set themselves as present in a meeting

**How to Reproduce**
1. open a meeting
2. open setting > participants > activate 'Allow users to set themselves as present'
3. open participants > add yourself to the meeting
4. open user profile and try to set yourself as present

**Expected behavior**
If the setting 'Allow users to set themselves as present' is activated, users should be able to set themselves as present in a meeting. 

**Additional context**

### PR DESCRIPTION
**Pull request by reiterl**
Resolve #4251

The user view was not updated anymore, this leads to problems in displaying the presence. I added the subscription code again. Now it works again.

### CODE REVIEW

**Review by Elblinator — APPROVED** [review]
functionality

**Comment by Elblinator** [comment]
This reverts part of the PR #3697 
https://github.com/OpenSlides/openslides-client/pull/3697/files#diff-48eb5aa2991c02ed994315afb345e9865bd4a134f0ff3c42fb17a04a12c6f329

File: client/src/app/site/modules/global-headbar/components/account-button/account-button.component.ts [hunk 1]
```diff
@@ -189,7 +189,22 @@ export class AccountButtonComponent extends BaseUiComponent implements OnInit {
...
-            this.user = this.operator.user;
+            this.doUserUpdate();
         }
     }
+
+    private doUserUpdate(): void {
+        if (!this._userId) {
+            this.user = null;
+            return;
+        }
```
Comment (Elblinator) [inline client/src/app/site/modules/global-headbar/components/account-button/account-button.component.ts:200]: this check seems unnecessary because in line 191 this.userId is defined as your own id

File: client/src/app/site/modules/global-headbar/components/account-button/account-button.component.ts [hunk 2]
```diff
@@ -189,7 +189,22 @@ export class AccountButtonComponent extends BaseUiComponent implements OnInit {
         const userId = this.operator.operatorId;
         if (this._userId !== userId) {
             this._userId = userId;
-            this.user = this.operator.user;
+            this.doUserUpdate();
         }
     }
+
+    private doUserUpdate(): void {
```
Comment (Elblinator) [inline client/src/app/site/modules/global-headbar/components/account-button/account-button.component.ts:196]: rename to sth more meaningful

**Review by Elblinator — CHANGES_REQUESTED** [review]

File: client/src/app/site/modules/global-headbar/components/account-button/account-button.component.ts (hunk 1 above)
Comment (reiterl) [reply client/src/app/site/modules/global-headbar/components/account-button/account-button.component.ts]: did another change.

File: client/src/app/site/modules/global-headbar/components/account-button/account-button.component.ts (hunk 2 above)
Comment (reiterl) [reply client/src/app/site/modules/global-headbar/components/account-button/account-button.component.ts]: no longer needed.

**Review by Elblinator — APPROVED** [review]

File: client/src/app/site/modules/global-headbar/components/account-button/account-button.component.ts [hunk 3]
```diff
@@ -117,11 +118,11 @@ export class AccountButtonComponent extends BaseUiComponent implements OnInit {
     }
 
     public toggleOperatorPresence(): void {
-        this.controller
+        this.userRepo
             .setPresent({
                 isPresent: !this.isPresent,
                 meetingId: this.activeMeetingId,
-                users: [this.user!]
+                users: [this.operator.user!]
```
Comment (bastianjoel) [inline client/src/app/site/modules/global-headbar/components/account-button/account-button.component.ts:125]:
```suggestion
                users: [this.user]
```

**Review by bastianjoel — APPROVED** [review]
