### PR TITLE
fix wrong poll percent no general options

### LINKED ISSUE #1613: Wrong percentage in election projections
* New election with two candidates
* Set max votes to 2
* Choose "Sum of votes without general options" as 100% base
* vote with at least two accounts (user A votes Opt1 and Opt2; user Bvotes Opt1)
* Publish and project

Result: Percentage for both candidates are 100%

### PR DESCRIPTION
**Pull request by bastianjoel**
resolves #1613

### CODE REVIEW

**Review by emanuelschuetze — APPROVED** [review]

File: client/src/app/site/pages/meetings/modules/projector/modules/slides/components/poll-slide/components/poll-slide.component.ts [hunk 1]
```diff
@@ -99,6 +99,7 @@ export class PollSlideComponent extends BaseSlideComponent<PollSlideData> {
         const poll: PollData = {
             getContentObjectTitle,
             pollmethod: data.pollmethod,
+            pollClassType: <PollClassType>data.content_object_id.split(`/`)[0],
```
Comment (jsangmeister) [inline client/src/app/site/pages/meetings/modules/projector/modules/slides/components/poll-slide/components/poll-slide.component.ts:102]: please use `collectionFromFqid`

**Review by jsangmeister — CHANGES_REQUESTED** [review]

**Review by rrenkert — APPROVED** [review]

**Review by jsangmeister — APPROVED** [review]
