### PR TITLE
Fix scrolling table viewport resizing

### LINKED ISSUE #2768: Fix missing autoupdate in Design-list
**Current behaviour:**
If you navigate from certain pages to the design page then only the first four design are displayed

**Recreation:**
1. have more than four designs
2. navigate to tags
3. navigate to design
4. only the first four designs are visible

**Wanted behaviour:**
All designs should always be displayed

### PR DESCRIPTION
**Pull request by luisa-beerboom**
Closes #2768

### CODE REVIEW

File: client/src/app/site/pages/organization/pages/designs/pages/design-main/components/design-main/design-main.component.ts [hunk 1]
```diff
@@ -10,6 +10,6 @@ import { getDesignListSubscriptionConfig } from '../../../../designs.subscriptio
 })
 export class DesignMainComponent extends BaseModelRequestHandlerComponent {
     protected override onShouldCreateModelRequests(): void {
-        this.subscribeTo(getDesignListSubscriptionConfig());
+        this.updateSubscribeTo(getDesignListSubscriptionConfig());
```
Comment (bastianjoel) [inline client/src/app/site/pages/organization/pages/designs/pages/design-main/components/design-main/design-main.component.ts:13]: This is reopening the subscription every time one accesses the design list. We do not want this.

**Review by bastianjoel — CHANGES_REQUESTED** [review]

**Comment by luisa-beerboom** [comment]
I looked into it again:
By superficially removing the cdk scroll viewport logic from the scrolling table components template and replacing it with a regular ngFor, I was able to stop it from displaying that behaviour.
So it seems to have something to do with the scroll viewport or its handling.

I'll see what I can do about it

**Review by bastianjoel — APPROVED** [review]

**Comment by bastianjoel** [comment]
Please update the title of the PR

**Review by rrenkert — APPROVED** [review]
