### PR TITLE
Fix linter warnings

### LINKED ISSUE #4885: Fix new linter warnings
[PR https://github.com/OpenSlides/openslides-client/pull/3427](https://github.com/OpenSlides/openslides-client/pull/4795) added new warnings

- [ ] @typescript-eslint/no-empty-object-type
- [x] @typescript-eslint/prefer-for-of
- [x] no-useless-escape
- [x] no-case-declarations
- [ ] no-async-promise-executor

we should continuously try to fix these warnings

### PR DESCRIPTION
**Pull request by Elblinator**
part of #4885

### CODE REVIEW

File: client/src/app/domain/models/action-worker/action-worker.ts [hunk 1]
```diff
@@ -28,4 +28,10 @@ export class ActionWorker extends BaseModel {
     ];
 }
 
-export interface ActionWorker {}
+export interface ActionWorker {
+    name: string;
+    state: ActionWorkerState;
+    created: number;
+    timestamp: number;
+    result?: any;
```
Comment (bastianjoel) [inline client/src/app/domain/models/action-worker/action-worker.ts:36]: We do not want this.

File: client/src/app/site/pages/meetings/pages/motions/view-models/view-motion-amended-paragraph.ts [hunk 2]
```diff
@@ -75,10 +75,9 @@ export class ViewMotionAmendedParagraph implements ViewUnifiedChange {
             case MergeAmendment.NO:
                 return false;
             default:
-                const mergeRecommendation = this.amendment.recommendation
+                switch (this.amendment.recommendation
```
Comment (bastianjoel) [inline client/src/app/site/pages/meetings/pages/motions/view-models/view-motion-amended-paragraph.ts:78]:
```suggestion
                switch (this.amendment.recommendation?.merge_amendment_into_final)
```

Comment (bastianjoel) [reply client/src/app/site/pages/meetings/pages/motions/view-models/view-motion-amended-paragraph.ts:78]: Also it might be better to change this to an `if` block.

File: client/src/app/site/pages/meetings/pages/motions/view-models/view-motion-amended-paragraph.ts [hunk 3]
```diff
@@ -101,19 +100,17 @@ export class ViewMotionAmendedParagraph implements ViewUnifiedChange {
     }
 
     public showInDiffView(): boolean {
-        const mergeState = this.amendment.state
+        switch (this.amendment.state
```
Comment (bastianjoel) [inline client/src/app/site/pages/meetings/pages/motions/view-models/view-motion-amended-paragraph.ts:103]: Same as above

**Review by bastianjoel — CHANGES_REQUESTED** [review]
Adding field definitions to models would make them much worse to maintain. 

If this is a problem for the linter we need another solution.

File: client/src/app/site/pages/meetings/pages/agenda/modules/topics/view-models/view-topic.ts [hunk 4]
```diff
@@ -52,4 +52,4 @@ export interface ViewTopic
     HasMeeting,
     ViewTopicRelations {}
 
-interface ViewTopicRelations extends HasPolls<ViewTopic> {}
+interface ViewTopicRelations extends HasPolls<ViewTopic> { null }
```
Comment (bastianjoel) [inline client/src/app/site/pages/meetings/pages/agenda/modules/topics/view-models/view-topic.ts:55]:
```suggestion
interface ViewTopicRelations extends HasPolls<ViewTopic> {}
```

File: client/src/app/domain/models/action-worker/action-worker.ts (hunk 1 above)
Comment (bastianjoel) [reply client/src/app/domain/models/action-worker/action-worker.ts:36]: In general

**Comment by Elblinator** [comment]
I change every switch to if at this place now 
Given your remarks this felt logical to do

**Review by bastianjoel — APPROVED** [review]
