### PR TITLE
Fix visual warning for deletion of a meeting

### LINKED ISSUE #4514: Protection against accidental deletion of an event
**Description:**
When working on a committee's meeting, the inhibition threshold for accidentally deleting a meeting is no higher than duplicating it.

**Expected behaviour:**
If the "OK" in the deletion-dialog is pressed an additional dialog should open itself and ask if the meeting should really be deleted,, pressing "OK" here should delete the meeting, pressing cancel should not delete the meeting

### PR DESCRIPTION
**Pull request by anbebe**
Closes #4514

### CODE REVIEW

**Review by reiterl — COMMENTED** [review]
I am not sure, if that works well with the translation.

File: client/src/app/ui/modules/prompt-dialog/components/prompt-dialog/prompt-dialog.component.ts [hunk 1]
```diff
@@ -18,4 +18,8 @@ export class PromptDialogComponent {
         public dialogRef: MatDialogRef<PromptDialogComponent>,
         @Inject(MAT_DIALOG_DATA) public data: PromptDialogData
     ) {}
+
+    public get canDelete(): boolean {
+        return this.data.confirm ? this.data.confirm.includes(`delete`) : false;
```
Comment (reiterl) [inline client/src/app/ui/modules/prompt-dialog/components/prompt-dialog/prompt-dialog.component.ts:23]: Mmh, what will happen, if 'delete' is translated somewhere above?

Comment (anbebe) [reply client/src/app/ui/modules/prompt-dialog/components/prompt-dialog/prompt-dialog.component.ts:23]: I think you are right and that it cannot be solved by checking the string but needs something different. I will take a look at it.

File: client/src/app/ui/modules/prompt-dialog/components/prompt-dialog/prompt-dialog.component.html [hunk 2]
```diff
@@ -3,7 +3,7 @@
         <h2 mat-dialog-title>{{ data.title | translate }}</h2>
         <mat-dialog-content [innerHTML]="data.content | translate"></mat-dialog-content>
         <mat-dialog-actions>
-            <button color="warn" mat-button [mat-dialog-close]="true" [ngClass]="{ delete: canDelete }">
+            <button color="warn" mat-button [mat-dialog-close]="true" [ngClass]="{ delete: data.deletion }">
```
Comment (reiterl) [inline client/src/app/ui/modules/prompt-dialog/components/prompt-dialog/prompt-dialog.component.html:6]: Does data always contain the deletion attribute? If no, try `?.` here.

**Review by reiterl — COMMENTED** [review]
Mmh. one remark. And the interface of the prompt service is growing.

File: client/src/app/ui/modules/prompt-dialog/components/prompt-dialog/prompt-dialog.component.html (hunk 2 above)
Comment (anbebe) [reply client/src/app/ui/modules/prompt-dialog/components/prompt-dialog/prompt-dialog.component.html:6]: No, deletion is not always contained in data but a ? is not necessary in this case since data always exists and the ngClass can handle undefined if deletion is not contained. That's how I understood it so far and it works.

**Review by reiterl — APPROVED** [review]
Looks Okay to Me

**Review by Elblinator — APPROVED** [review]
