### PR TITLE
Remove check-database buttons and presenter call

### LINKED ISSUE #6080: Remove Superadmin actions in impressum
**Current behavior**
Currently the buttons so check the datastore is still displayed

Image

**Wanted behavior**
The tiel Superadmin actions and the two buttons below should be removed

**Additionally:**
Since rel-db they do not work anymore and are not intended to work anymore, hence, they shouldd be removed

### PR DESCRIPTION
**Pull request by reiterl**
Resolve #6080

### CODE REVIEW

File: client/src/app/site/modules/info/components/info-actions/info-actions.component.ts [hunk 1]
```diff
@@ -14,8 +12,6 @@ import { LifecycleService } from 'src/app/site/services/lifecycle.service';
 export class InfoActionsComponent extends BaseComponent {
     public constructor(
         private lifecycleService: LifecycleService,
-        private snackbar: MatSnackBar,
-        private presenter: CheckDatabasePresenterService,
         protected override translate: TranslateService
```
Comment (Elblinator) [inline client/src/app/site/modules/info/components/info-actions/info-actions.component.ts]:
```suggestion
```

File: client/src/app/site/modules/info/components/info-actions/info-actions.component.ts [hunk 2]
```diff
@@ -1,7 +1,5 @@
 import { Component } from '@angular/core';
-import { MatSnackBar } from '@angular/material/snack-bar';
 import { TranslateService } from '@ngx-translate/core';
```
Comment (Elblinator) [inline client/src/app/site/modules/info/components/info-actions/info-actions.component.ts]:
```suggestion
```

**Review by Elblinator — CHANGES_REQUESTED** [review]

File: client/src/app/site/modules/info/components/info-actions/info-actions.component.ts (hunk 1 above)
Comment (reiterl) [reply client/src/app/site/modules/info/components/info-actions/info-actions.component.ts]: done

File: client/src/app/site/modules/info/components/info-actions/info-actions.component.ts (hunk 2 above)
Comment (reiterl) [reply client/src/app/site/modules/info/components/info-actions/info-actions.component.ts]: done.

**Comment by reiterl** [comment]
Also removed the TranslateService.

**Review by Elblinator — APPROVED** [review]
code and function
