### PR TITLE
Fixes selecting the right group in the user-list

### LINKED ISSUE #312: `<group-search-value-selector />` to filter default groups

### PR DESCRIPTION
**Pull request by GabrielInTheWorld**
Fixes #312 since a dedicated component is not necessary.

### CODE REVIEW

File: client/src/app/site/users/components/user-list/user-list.component.ts [hunk 1]
```diff
@@ -92,7 +92,7 @@ export class UserListComponent extends BaseListViewComponent<ViewUser> implement
     /**
      * All available groups, where the user can be in.
      */
-    public groups: ViewGroup[];
+    public groupsObservable?: Observable<ViewGroup[]>;
```
Comment (tsiegleauq) [inline client/src/app/site/users/components/user-list/user-list.component.ts:95]:
```suggestion
    public groupsObservable?: Observable<ViewGroup[]> = this.groupRepo.getViewModelListObservableWithoutDefaultGroup();
```

File: client/src/app/site/users/components/user-list/user-list.component.ts [hunk 2]
```diff
@@ -213,13 +213,7 @@ export class UserListComponent extends BaseListViewComponent<ViewUser> implement
...
 
         // Initialize the groups
-        this.groups = this.groupRepo.getViewModelList().filter(group => group.id !== 1);
-
-        this.subscriptions.push(
-            this.groupRepo
-                .getViewModelListObservable()
-                .subscribe(groups => (this.groups = groups.filter(group => group.id !== 1)))
-        );
+        this.groupsObservable = this.groupRepo.getViewModelListObservableWithoutDefaultGroup();
```
Comment (tsiegleauq) [inline client/src/app/site/users/components/user-list/user-list.component.ts:216]:
```suggestion
```

**Review by tsiegleauq — APPROVED** [review]
alternatively, but does not really matter
