### PR TITLE
Fix sorting by category

### LINKED ISSUE #2056: Sort motions by category is broken
**Reproduction:**
* Requires multiple motions with categories (and sub categories) e.g. A, A1, A2, B, B1, C, C1
* Motion have both, the category and a subcategory
* Sort motions by category
Now the motions order in tests was 
1. Motion with category A+A1
2. Motion with category B+B1
3. Motion with category C+C1
4. Motion with category C+C1
5. Motion with category A+A2
6. Motion with category A+A2 
7. Motion with category B+B2
8. Motion with category B+B2

Expected:
1. Motion with category A+A1
2. Motion with category A+A2
3. Motion with category A+A2
4. Motion with category B+B1
5. Motion with category B+B2
6. Motion with category B+B2 
7. Motion with category C+C1
8. Motion with category C+C1

### PR DESCRIPTION
**Pull request by jsangmeister**
fixes #2056

### CODE REVIEW

File: client/src/app/site/pages/meetings/pages/motions/modules/categories/view-models/view-motion-category.ts [hunk 1]
```diff
@@ -69,21 +74,6 @@ export class ViewMotionCategory extends BaseViewModel<MotionCategory> /* impleme
...
-     */
-    public collectParents(): ViewMotionCategory[] {
-        if (this.parent) {
-            const parents = this.parent.collectParents();
-            parents.unshift(this.parent);
-            return parents;
-        } else {
-            return [];
-        }
-    }
```
Comment (jsangmeister) [inline client/src/app/site/pages/meetings/pages/motions/modules/categories/view-models/view-motion-category.ts:86]: Removed this since it is functionally equivalent to `allParents`, as far as i can see.

**Review by luisa-beerboom — APPROVED** [review]

**Comment by emanuelschuetze** [comment]
@rrenkert I cannot reproduce your origin issue. -> needs discussion

**Comment by jsangmeister** [comment]
@emanuelschuetze see https://github.com/OpenSlides/openslides-client/issues/2056#issuecomment-1457716752. Works still in the current demo. Removing the "needs discussion" label

**Review by rrenkert — APPROVED** [review]
