### PR TITLE
Search bar now filters by sequential number instead of id

### LINKED ISSUE #1114: Text search (for at least motions) in list views is broken
For motions:
Trying to filter by their sequential numbers does not work - instead they are filtered by their id...

### PR DESCRIPTION
**Pull request by luisa-beerboom**
Closes #1114

### CODE REVIEW

File: client/src/app/ui/modules/list/components/list/list.component.ts [hunk 1]
```diff
@@ -560,11 +560,11 @@ export class ListComponent<V extends Identifiable> implements OnInit, OnDestroy
                 return true;
             }
 
-            // filter by ID
+            // filter by sequential number
             const trimmedInput = this.inputValue.trim().toLowerCase();
-            const idString = `` + item.id;
```
Comment (GabrielInTheWorld) [inline client/src/app/ui/modules/list/components/list/list.component.ts:565]: Pay attention here: Keep in mind, that there are models without a `sequential_number`

**Review by GabrielInTheWorld — CHANGES_REQUESTED** [review]

**Review by GabrielInTheWorld — APPROVED** [review]
It is okay for me. I'm still not quite comfortable with the name. Maybe we can change it someday.

**Comment by GabrielInTheWorld** [comment]
@emanuelschuetze: These changes work fine. Feel free to merge this PR.

**Review by emanuelschuetze — APPROVED** [review]
