### PR TITLE
Fixes setting the presence of users

### LINKED ISSUE #395: user bulk set present broken
No options, error is thrown on OK.

```
Uncaught (in promise): TypeError: Cannot read property '0' of undefined
TypeError: Cannot read property '0' of undefined
    at UserListComponent.<anonymous> (user-list.component.ts:403)
```

image

### PR DESCRIPTION
**Pull request by GabrielInTheWorld**
- Also changes the "setPresent"-function in the user-repo so, that a list of users can be passed

Fixes #395

### CODE REVIEW

File: client/src/app/site/users/components/user-list/user-list.component.ts [hunk 1]
```diff
@@ -441,7 +423,41 @@ export class UserListComponent extends BaseListViewComponent<ViewUser> implement
...
+                options = [_('active'), _('inactive')];
+                verboseStateName = 'active';
+                break;
+            case 'is_present_in_meetings':
+                options = [_('present'), _('absent')];
+                verboseStateName = 'present';
+                break;
+            case 'is_physical_person':
+                options = [_('natural person'), _('no natural person')]; // switched order: no committee=physical person
+                verboseStateName = 'committee';
```
Comment (FinnStutzenstein) [inline client/src/app/site/users/components/user-list/user-list.component.ts:448]: can you also rename `committee` here, so all logical connections to OS3 are gone?

**Review by FinnStutzenstein — APPROVED** [review]
Code looks good!

File: client/src/app/site/users/components/user-list/user-list.component.ts (hunk 1 above)
Comment (GabrielInTheWorld) [reply client/src/app/site/users/components/user-list/user-list.component.ts]: I just removed the `verboseStateName` since it is never used.
