### PR TITLE
Fix autoupdate handleError error type check

### LINKED ISSUE #3071: Re-Login problem after logout
**Description:** If a user is in a meeting and logs out of it, an error occurs when logging in again directly. The login page displays a permanent spinning wheel. Logging in is only possible after reloading the page. When reloading, the user is logged in directly. 

**Reproduction:**
1. open a meeting
2. log out
3. log in
4. -> spinning wheel appears.

**What should happen:**
Logging should be possible without a page reload and without a permanent spinning wheel.

### PR DESCRIPTION
**Pull request by bastianjoel**
Client errors are currently not correctly handled by the shared worker. This could result in unexpected behavior when the autoupdate reports an client error. 

resolves #3071

### CODE REVIEW

**Review by luisa-beerboom — APPROVED** [review]

**Comment by bastianjoel** [comment]
Test are failing now because of https://github.com/OpenSlides/openslides-autoupdate-service/issues/789

File: client/src/app/gateways/http-stream/http-stream.ts [hunk 1]
```diff
@@ -327,10 +328,10 @@ export class HttpStream<T> {
     }
 
     private async handleStreamError(error: unknown): Promise<void> {
+        console.log(error);
```
Comment (luisa-beerboom) [inline client/src/app/gateways/http-stream/http-stream.ts:331]: delete

**Review by Elblinator — APPROVED** [review]
