### PR TITLE
Fixes tile view

### LINKED ISSUE #216: The tile-view for motions does not work properly
Only the non-category `Unset` is shown. To fix this, the information `parent_id`, `child_ids` and `motion_ids` has to be loaded. Furthermore, a recursively dependency from child_ids to their children has to be resolved.

Depends on #228.

### PR DESCRIPTION
**Pull request by GabrielInTheWorld**
Fixes #216.

Depends on #231.

### CODE REVIEW

File: client/src/app/site/motions/modules/motion-list/components/motion-list/motion-list.component.ts [hunk 1]
```diff
@@ -324,6 +324,11 @@ export class MotionListComponent extends BaseListViewComponent<ViewMotion> imple
                     ],
                     fieldset: 'list',
                     additionalFields: ['text']
+                },
+                {
+                    idField: 'motion_category_ids',
+                    fieldset: 'list',
+                    follow: ['parent_id', 'child_ids']
```
Comment (FinnStutzenstein) [inline client/src/app/site/motions/modules/motion-list/components/motion-list/motion-list.component.ts:331]: You do not have to follow them, just request them as either additional fields or create a fieldset. This is because all categories are already included in the request itself; the ids are needed by the client for the relations itself.

**Review by FinnStutzenstein — APPROVED** [review]
