### PR TITLE
Fix vote weight 0 not displayed

### LINKED ISSUE #3033: Vote_weight: Fix wrong display and export
**Current behaviour:**
If a participant was saved with vote_weight: 0 in the past (which was allowed in the past, but not anymore) then the vote weight is displayed as as "vote weight: 1"

**Wanted behaviour:**
the vote weight should be correctly displayed

### PR DESCRIPTION
**Pull request by bastianjoel**
resolves #3033

### CODE REVIEW

File: client/src/app/site/pages/meetings/view-models/view-user.ts [hunk 1]
```diff
@@ -198,7 +198,8 @@ export class ViewUser extends BaseViewModel<User> /* implements Searchable */ {
     }
 
     public vote_weight(meetingId?: Id): number {
-        return this.getMeetingUser(meetingId)?.vote_weight || this.default_vote_weight;
+        const mUserVoteWeight = this.getMeetingUser(meetingId)?.vote_weight;
+        return mUserVoteWeight || mUserVoteWeight === 0 ? mUserVoteWeight : this.default_vote_weight;
```
Comment (luisa-beerboom) [inline client/src/app/site/pages/meetings/view-models/view-user.ts:202]:
```suggestion
        return mUserVoteWeight ?? this.default_vote_weight;
```

Wouldn't this work too?

Comment (bastianjoel) [reply client/src/app/site/pages/meetings/view-models/view-user.ts:202]: Yes

**Review by luisa-beerboom — APPROVED** [review]
