### PR TITLE
FIX Navigation Between Motions and Amendments

### LINKED ISSUE #3177: Motions and amendment list: navigation has issues
**Description:** The navigation in the motion and amendment list view has some issues.

- [x] Case A: Motion list view: If 'Show amendments together with motions' is activated in Settings > Motions and you have opened an amendment, the main motion is opened instead of the motion list when you click on the Back-button.
- [x] Case B1: amendment list view: The navigation between all amendments is not possible. The navigation is currently limited inbetween amendments which are associated with the same parent motion. 
- [x] Case B2: amendment list view: If 'Show amendments together with motions' is activated in Settings > Motions is activated, the parent motions became invisible available in the amendment list. By navigating from amendment to amendment, it is now possible to navigate to a parent motion. And by doing it and clicking the Back-button, the motion list is opened. 

**Reproduction:**
1. open a meeting
2. open motions: create two motions with two amendments
3. open settings > motions > activate "Show amendments together with motions"
4. open motions: open the first motion and navigate to the seond amendment. Use the Back-button to open the motion list. The first amendment is now opened. Click again on back-button and the parent motion is opened. (Case A)
5. open amendment list: open first amendment and navigate to the next one until you have opened a parent motion (Case B2)
6. open settings > motions > deactivate "Show amendments together with motions"
7. open the amendment list view: try to navigate between the amendments. (Case B1)

**What should happen:**
Case A: By clicking the Back-button, the motion list should be opened, not the parent motion of an amendment.
Case B1: The navigation should be possible between all visible amendments.
Case B2: If 'Show amendments together with motions' is activated, it should not be possible in the amendment list to open a parent motion.  

**Hint:** B1 and B2 are linked to the issue #2926 . The navigation logic should follow WYSIWYG. The navigation is always related to the content the user see.

### PR DESCRIPTION
**Pull request by reicda**
closes #3177

### CODE REVIEW

File: client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-view/motion-detail-view.component.ts [hunk 1]
```diff
@@ -302,16 +321,51 @@ export class MotionDetailViewComponent extends BaseMeetingComponent implements O
         const indexOfCurrent = this._sortedMotions.findIndex(motion => motion === this.motion);
         if (indexOfCurrent > 0) {
             this.previousMotion = this._sortedMotions[indexOfCurrent - 1];
+            this.substituteSurroundingMotions(indexOfCurrent, true);
```
Comment (bastianjoel) [inline client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-view/motion-detail-view.component.ts:324]: I guess it would be better to just set the correct value instead of correcting it afterwards.

File: client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-view/motion-detail-view.component.ts [hunk 2]
```diff
@@ -302,16 +321,51 @@ export class MotionDetailViewComponent extends BaseMeetingComponent implements O
...
+     * Substitutes the previous or next motion.
+     * Fires if @var this._amendmentsInMainList as well as @var this._navigatedFromAmendmentList collide.
+     * @param indexOfCurrent The index from the active motion.
+     * @param previous Wether the method is called for the previous or the next motion.
+     */
+    private substituteSurroundingMotions(indexOfCurrent: number, previous: boolean) {
+        if (this._amendmentsInMainList && this._navigatedFromAmendmentList) {
+            let index = indexOfCurrent;
+            if (!previous) {
+                while (index < this._sortedMotions.length - 1) {
```
Comment (bastianjoel) [inline client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-view/motion-detail-view.component.ts:346]: I'd prefer a for loop here. When changing this to return the next suitable motion it should also be possible to reduce this into one loop.

**Review by bastianjoel — CHANGES_REQUESTED** [review]

File: client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-view/motion-detail-view.component.ts [hunk 3]
```diff
@@ -301,17 +320,36 @@ export class MotionDetailViewComponent extends BaseMeetingComponent implements O
...
             this.nextMotion = null;
         }
     }
 
+    /**
+     * Substitutes the previous or next motion.
+     * Fires if @var this._amendmentsInMainList as well as @var this._navigatedFromAmendmentList collide.
+     * @param indexOfCurrent The index from the active motion.
+     * @param previous Wether the method is called for the previous or the next motion.
+     */
```
Comment (bastianjoel) [inline client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-view/motion-detail-view.component.ts:339]: Doc needs to be updated or removed. For private methods it is normally okay to not add a docblock.

**Review by bastianjoel — APPROVED** [review]
Looks good! Just one minor remark.

**Review by Elblinator — CHANGES_REQUESTED** [review]
If a motion is created then the arrow navigation is from the amendment-list is shown.

Please make sure that the correct navigation is shown after creating a motion/amendment:
- A) If a motion is created then the arrows/navigation from the motion-list should be shown  
- B) if an amendment is created and amendments are shown together with motions the arrows from the motion-list should be shown 
- C) if an amendment is created and amendments are NOT shown together with motions then the arrows from the amendment-list should be shown (this already happens but could change if A and B are implemented)

**Review by Elblinator — APPROVED** [review]
