### PR TITLE
Hide forward menu entry same as forward button

### LINKED ISSUE #4896: Hide "Forward"-Option if motion cannot be forwarded
**Describe the bug**
The "Foward" button in a motion-detail view is displayed in the three dot menu if the motion is in a forwardable state. Even if the motion cannot be forwarded due to no metting to forward to or because the motion was already forwarded to all available meetings

**How to Reproduce**
1. Two Committees (First and Second)
2. Allow second to forward to first
3. create a meeting in both committees
4. Navigate into first allow to forward a motion in the simple workflow "submitted"
5. Create a motion and navigate into it's detail view
6. Motion-detail > three-dot-menu > press forward
7. The dialog shows every option but a meeting to forward to 
8. Navigate into the meeting "second"
9. allow to forward a motion in the simple workflow "submitted"
10. Create a motion and forward it to "first"
11. Reload the page and open the forward dialog again
12. You cannot press any meeting bc the motion awas already forwarded to every meeting

**Expected behavior**
The forward option should be hidden i nstep 6 and 11 
-> if there is no meeting to forward to (bc there is none or bc the motion was already forwarded to every meeting) then the forward option should not be displayed

### PR DESCRIPTION
**Pull request by reiterl**
Resolve #4896 

The calculation between the 'Forward' button and the 'Forward' menu entry (in 3-point-menu) was different.
I tried to unify this.

### CODE REVIEW

**Comment by reiterl** [comment]
I moved the `showForwardButton` calculation into the `motion-view` component. That cleans up repeated code.

**Review by Elblinator — CHANGES_REQUESTED** [review]
If a motion can be forwarded into two meetings (A and B) then in the current version the dialog cannot be opened after forwarding the motion into A

If a participant has the permission to forward then this participant cannot see the button in the three dot menu. 
Additionally: This participant cannot see the button in the motion detail view, that was alreay an issue before. If possible pls fix also here if that doesn't belong here please say so and I'll create it's own issue

**Comment by reiterl** [comment]
I have split the two method `showForwardMenuEntry` and `showForwardButton`. The menu entry can be seen, even the motion was already forwarded. 

In my test a participant with 'can forward motion' like in the staff group can see button and menu entry.
Perhaps open an new issue with steps for the second part.

File: client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-view/motion-view.component.ts [hunk 1]
```diff
@@ -181,6 +194,13 @@ export class MotionViewComponent extends BaseMeetingComponent implements OnInit,
                 )
                 .subscribe(() => this.onMotionChange())
         );
+
+        if (operator.hasPerms(Permission.motionCanManageMetadata)) {
```
Comment (Elblinator) [inline client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-view/motion-view.component.ts:198]:
```suggestion
        if (operator.hasPerms(Permission.motionCanForward)) {
```

**Review by Elblinator — CHANGES_REQUESTED** [review]
If a motion was forwarded to all Meetings and cannot be forwarded anymore then the button is still in the three dot menu

If a motion cannot be forwarded to any meeting anymore then the button should also be hidden

File: client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-view/motion-view.component.ts (hunk 1 above)
Comment (reiterl) [reply client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-view/motion-view.component.ts]: Done.

**Review by Elblinator — APPROVED** [review]
function

**Review by bastianjoel — APPROVED** [review]
