### PR TITLE
Scrolling table deselectAll works now

### LINKED ISSUE #1318: Lists: Deselect all broken
Instead of switching all options off, it inverts them instead.

### PR DESCRIPTION
**Pull request by luisa-beerboom**
Closes #1318

### CODE REVIEW

File: client/src/app/ui/modules/scrolling-table/components/scrolling-table/scrolling-table.component.ts [hunk 1]
```diff
@@ -220,7 +220,9 @@ export class ScrollingTableComponent<T extends Partial<Mutable<Identifiable>>>
     private onBeforeSelectionChanged(rows: T[], isChecked?: boolean): void {
         for (const row of rows) {
             const index = row.id;
-            this._dataSourceMap[index].isSelected = isChecked || !this._dataSourceMap[index].isSelected;
+            this._dataSourceMap[index].isSelected = [true, false].includes(isChecked)
+                ? isChecked
+                : !this._dataSourceMap[index].isSelected;
```
Comment (jsangmeister) [inline client/src/app/ui/modules/scrolling-table/components/scrolling-table/scrolling-table.component.ts:225]:
```suggestion
            this._dataSourceMap[index].isSelected = isChecked ?? !this._dataSourceMap[index].isSelected;
```
doesn't this also do the trick? the `[true, false].includes` looks kinda hacky

**Review by jsangmeister — APPROVED** [review]

**Comment by emanuelschuetze** [comment]
Deselect all works already in main branch. Is this fix really required?

**Review by emanuelschuetze — APPROVED** [review]
works as expected
