### PR TITLE
#1025 Login: Added function to trim white space from username

### LINKED ISSUE #1025: Login fails because the username of a user is surrounded by spaces.

### PR DESCRIPTION
**Pull request by luisa-beerboom**
Closes #1025

Added a small function that trims the white space off the ends of the username.

### CODE REVIEW

File: client/src/app/site/login/components/login-mask/login-mask.component.ts [hunk 1]
```diff
@@ -162,14 +162,19 @@ export class LoginMaskComponent extends BaseComponent implements OnInit, OnDestr
...
-            const { username, password }: { username: string; password: string } = this.loginForm.value;
+            const { username, password }: { username: string; password: string } = this.formatLoginInputValues(this.loginForm.value);
             await this.authService.login(username, password, this.currentMeetingId);
         } catch (e) {
             this.spinnerService.hide();
             this.loginErrorMsg = e;
         }
     }
 
+    private formatLoginInputValues(info: {username: string; password: string}): { username: string; password: string }{
```
Comment (GabrielInTheWorld) [inline client/src/app/site/login/components/login-mask/login-mask.component.ts:173]: Please create an interface to describe the login values.

**Review by GabrielInTheWorld — CHANGES_REQUESTED** [review]
One remark.

**Comment by GabrielInTheWorld** [comment]
Keep in mind that you should run `npm run cleanup`.

**Review by GabrielInTheWorld — APPROVED** [review]

**Review by emanuelschuetze — APPROVED** [review]
