### PR TITLE
Made motion detail recognize if the text is loaded

### LINKED ISSUE #2198: After opening the detail view of an motion, "undefined" is displayed instead of the motion text
`.../.../motions/...`

### Bug description
- After opening the detail view of an motion, "undefined" is displayed instead of the motion text. A few seconds later the motion text is loaded - depending on the user's network/device, length of the text and size of the instance. This worries users and makes them assume the text has disappeared or something.
- According to Emanuel, this behavior seems to be a follow-up effect of the change made to the Auto Update service (motion texts are loaded only when the detail view is clicked)

### Expected behavior
- When the motion text is loading, a loading bar is displayed to make it clear to users: there's still something coming, it's loading, it's not gone.
- The loading bar is visible at the very top inside the motion text tile and across the entire width until the text is fully loaded.
- Please use @angular/material/progress-bar
  - color: ThemePalette = 'primary';
  - mode: ProgressBarMode = 'indeterminate';
  - value = 50;
  - bufferValue = 75;
- Like this

Apr-13-2023 15-48-09

### Additional context
OpenSlides: → 4.0.1-main-20230405-096d7db

### PR DESCRIPTION
**Pull request by luisa-beerboom**
Closes #2198

### CODE REVIEW

**Review by emanuelschuetze — APPROVED** [review]

File: client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-original-change-recommendations/motion-detail-original-change-recommendations.component.ts [hunk 1]
```diff
@@ -100,13 +108,31 @@ export class MotionDetailOriginalChangeRecommendationsComponent implements OnIni
...
+        this.autoupdateCommunications
+            .listen()
+            .pipe(
+                filter(data => data.description === MOTION_DETAIL_SUBSCRIPTION),
+                delay(500)
+            )
+            .subscribe(data => {
+                this.dataLoaded = true;
+                this.update();
+            });
```
Comment (bastianjoel) [inline client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/components/motion-detail-original-change-recommendations/motion-detail-original-change-recommendations.component.ts:135]: The subscription could be closed after the first value was received.

**Review by bastianjoel — CHANGES_REQUESTED** [review]

**Review by bastianjoel — APPROVED** [review]

**Review by emanuelschuetze — APPROVED** [review]
