### PR TITLE
fix livestream sometimes not displayed

### LINKED ISSUE #2189: The live stream and video conference interface is not displayed
* Set the jitsi domain and the jitsi room name in the meeting settings. (Three points menu in the committee overview)
* Open the meeting, go to Settings -> Livestream and set a Livestream URL. (e.g. a YouTube Livestream) 
* Set the check mark at "Show live conference window".
* Set the check mark at "Allow only current speakers and list of speakers managers to enter the live conference"
* Log in with a user who does not have the right to manage the speakers list.
* Reload the page and the interface is gone.

If "Allow only current speakers and list of speakers managers to enter the live conference" is turned off again or the user is put on the speakers list the interface is there again.

### PR DESCRIPTION
**Pull request by bastianjoel**
resolves #2189

### CODE REVIEW

**Review by luisa-beerboom — APPROVED** [review]

File: client/src/app/site/pages/meetings/services/active-meeting.subscription.ts [hunk 1]
```diff
@@ -51,6 +52,34 @@ export function getActiveMeetingSubscriptionConfig(id: Id, settingsKeys: string[
...
+                            idField: `current_projection_ids`,
+                            fieldset: [...MEETING_ROUTING_FIELDS],
+                            follow: [
+                                {
+                                    idField: `content_object_id`,
+                                    fieldset: [...MEETING_ROUTING_FIELDS],
+                                    follow: [
+                                        {
+                                            idField: `list_of_speakers_id`,
+                                            fieldset: [...MEETING_ROUTING_FIELDS],
```
Comment (luisa-beerboom) [inline client/src/app/site/pages/meetings/services/active-meeting.subscription.ts:70]: Do you really need to request the sequential number and meeting id for all of these? If not, couldn't you just leave them out and not request any fields for the connective models at all?

**Review by luisa-beerboom — CHANGES_REQUESTED** [review]
Generally looks good to me, just one question

**Comment by bastianjoel** [comment]
Mind that it is possible that this still sometimes does not work because of https://github.com/OpenSlides/openslides-autoupdate-service/issues/666

**Review by m-schieder — APPROVED** [review]
