### PR TITLE
Fix: Sets vote_weight to 0

### LINKED ISSUE #866: Cannot set a user's vote weight to `0`

### PR DESCRIPTION
**Pull request by GabrielInTheWorld**
Fixes #866

### CODE REVIEW

File: client/src/app/site/users/components/user-detail/user-detail.component.ts [hunk 1]
```diff
@@ -115,7 +115,11 @@ export class UserDetailComponent extends BaseModelContextComponent implements On
     public readonly users: BehaviorSubject<ViewUser[]> = new BehaviorSubject<ViewUser[]>([]);
 
     public get showVoteWeight(): boolean {
-        return this.pollService.isElectronicVotingEnabled && this._voteWeightEnabled;
+            return (
```
Comment (emanuelschuetze) [inline client/src/app/site/users/components/user-detail/user-detail.component.ts:118]: looks like this indentation is not correct

Comment (emanuelschuetze) [inline client/src/app/site/users/components/user-detail/user-detail.component.ts:118]: looks like this indentation is not correct

**Review by emanuelschuetze — APPROVED** [review]
