### PR TITLE
make mediafile folders accessable via url

### LINKED ISSUE #2270: Links and url navigation to mediafile folders do not work
Reproduction:
1. In a meeting open the mediafile list and create a folder
2. Navigate into the folder
3. Copy the url of the page
4. Open a new tab
5. Paste the url into the url bar to try and navigate to the page
=> The navigation will lead to the url of the home directory, not the sub-directory that was intended

### PR DESCRIPTION
**Pull request by bastianjoel**
resolves #2270

### CODE REVIEW

**Review by luisa-beerboom — APPROVED** [review]

File: client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-list/components/mediafile-list/mediafile-list.component.ts [hunk 1]
```diff
@@ -171,7 +172,13 @@ export class MediafileListComponent extends BaseMeetingListViewComponent<ViewMed
         return false;
     }
 
-    public changeDirectory(directoryId: number | null): void {
+    public async changeDirectory(directoryId: number | null): Promise<void> {
+        const mediafilesSubscribed = await this.modelRequestService.subscriptionGotData(MEDIAFILES_SUBSCRIPTION);
```
Comment (jsangmeister) [inline client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-list/components/mediafile-list/mediafile-list.component.ts:176]: Shouldn't this wait until data was received? Or why is the timeout below necessary?

Independently, please introduce a common base class to not duplicate the function code. You can probably combine even more functionality in that, I did not look through the rest of the classes.

**Review by jsangmeister — CHANGES_REQUESTED** [review]

File: client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-list/components/mediafile-list/mediafile-list.component.ts (hunk 1 above)
Comment (bastianjoel) [reply client/src/app/site/pages/meetings/pages/mediafiles/modules/mediafile-list/components/mediafile-list/mediafile-list.component.ts:176]: It is possible that the subscription was not opened yet. In that case `subscriptionGotData` returns false. 

I second that but I think we should open another issue for that.

**Review by jsangmeister — APPROVED** [review]

**Review by emanuelschuetze — APPROVED** [review]
