### PR TITLE
Quick fix

### LINKED ISSUE #794: Implement relations for committee managers
If #793 is merged,

```js
    // ...makeManyStructuredUsers2MRelation({
    //     otherViewModel: ViewCommittee,
    //     structuredField: `committee_management_levels`,
    //     structuredIdField: `committee_$_management_level`,
    //     otherViewModelField: `user_management_levels`,
    //     otherViewModelIdField: `user_$_management_level`
    // }),
```

this should be tackled in another PR.

_Originally posted by @GabrielInTheWorld in https://github.com/OpenSlides/openslides-client/pull/793#r794549252_

### LINKED ISSUE #832: Iterating over committees respectively managers breaks the site
- [x] Maybe account/committees is not available
- [ ] Maybe committee/managers is not available (#794)

### PR DESCRIPTION
**Pull request by GabrielInTheWorld**
Fixes #832 

This is just a quick fix for the relation committee/managers (used in the committee-detail view). We have to do #794!

### CODE REVIEW

File: client/src/app/management/components/committee-detail/committee-detail.component.ts [hunk 1]
```diff
@@ -92,6 +92,8 @@ export class CommitteeDetailComponent extends BaseModelContextComponent implemen
             viewModelCtor: ViewCommittee,
             ids: [this.committeeId],
             follow: [
+                { idField: `user_ids`, fieldset: `shortName` },
```
Comment (GabrielInTheWorld) [inline client/src/app/management/components/committee-detail/committee-detail.component.ts:95]: This line can be deleted, if the line below works.
