### PR TITLE
Fix & beautify workflow detail view

### LINKED ISSUE #1389: Changes in workflow only visible after clicking somewhere else
Changes in the workflow are not visible until the user clicks somewhere else on the web page. 

Reproduction.

1. Open workflow in meeting
2. change status color of submitted (or something else) -> nothing happens
3. Click somewhere else. Change becomes active.

What should happen: Changes becomes instantly active by clicking.

### PR DESCRIPTION
**Pull request by jsangmeister**
fixes #1389 

I switched the change detection back to the default one, because this seemed to work way better. I don't know what the initial reasoning was for the `OnPush` method.

I also beautified the view by removing the space before the colon and fixing the sticky rows/columns. I removed a section from `tables.scss` for that, which might also influence other tables - I didn't find any problems, but it would be good to double-check it.

### CODE REVIEW

**Comment by jsangmeister** [comment]
Also, I noticed that you can't change the first state of a workflow, while we have this functionality in the backend. Is this intended or just missing? @emanuelschuetze

**Comment by emanuelschuetze** [comment]
> Also, I noticed that you can't change the first state of a workflow, while we have this functionality in the backend. Is this intended or just missing? @emanuelschuetze

Right, this is still missing in client. Issue created: https://github.com/OpenSlides/openslides-client/issues/1403
But its a low one.

**Review by emanuelschuetze — APPROVED** [review]
looks good

File: client/src/app/site/pages/meetings/pages/motions/pages/workflows/components/workflow-detail/workflow-detail.component.ts [hunk 1]
```diff
@@ -121,8 +120,9 @@ export class WorkflowDetailComponent extends BaseMeetingComponent {
 
     private set workflow(workflow: ViewMotionWorkflow) {
         this._workflow = workflow;
+        console.log(`Workflow set:`, workflow);
```
Comment (luisa-beerboom) [inline client/src/app/site/pages/meetings/pages/motions/pages/workflows/components/workflow-detail/workflow-detail.component.ts:123]: Could it be that you forgot to remove this?

**Review by luisa-beerboom — COMMENTED** [review]
Looks alright, but...

File: client/src/app/site/pages/meetings/pages/motions/pages/workflows/components/workflow-detail/workflow-detail.component.ts (hunk 1 above)
Comment (emanuelschuetze) [reply client/src/app/site/pages/meetings/pages/motions/pages/workflows/components/workflow-detail/workflow-detail.component.ts:123]: I'll remove this line.
