### PR TITLE
Fixes about me and race conditions in user-detail-view

### LINKED ISSUE #364: "About me" and "vote delegated to/from" do not work in the user-detail-view

### PR DESCRIPTION
**Pull request by GabrielInTheWorld**
- The template-field "about_me_$" is requested
- Prevents a race condition in the user-detail-view: A function to request a user's information was invoked two times independently from each other.

Fixes #364

### CODE REVIEW

File: client/src/app/site/users/components/user-detail/user-detail.component.ts [hunk 1]
```diff
@@ -141,6 +142,11 @@ export class UserDetailComponent extends BaseModelContextComponent implements On
     }
 
     private loadUserById(): void {
+        // Prevent race conditions since this method is invoked two times.
```
Comment (FinnStutzenstein) [inline client/src/app/site/users/components/user-detail/user-detail.component.ts:145]: This is not the solution. Use observables. Some lines above are two calls to this function. You can merge both observables. Also awaiting this.request models can prevent the race condition (do it aditionally)

**Review by FinnStutzenstein — CHANGES_REQUESTED** [review]

**Review by FinnStutzenstein — APPROVED** [review]
Looks good, not tested
