### PR TITLE
Prevent failure by broken change recommendation

### LINKED ISSUE #4679: Fix inconsistencies between change recommendations and motion edits
**Describe the bug**
Deleting lines in a motion while a change recommendation is made on those lines, results in inconsistent data in the motion: 

> Inconsistent data. A change recommendation or amendment is probably referring to a non-existant line number.

It is neither possible to view the change recommendation (and edit or delete it), change the display version of the motion or edit the motion. 
Error only appears when Diff version is selected as default in the motion settings. 

**How to Reproduce**
1. create a motion (see below for source code)
2. create a change rec in the last lines of the motion and save it (see below)
3. edit the motion (see below in how)
4. save the motion
5. reload the page motion detail page
6. The whole motion is displayed as the following: 
```
Inconsistent data. A change recommendation or amendment is probably referring to a non-existant line number.
```

Motion text: 
```
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc,</p>
```

Change recommendation on line 17: 
```
<p>sodales, augue velit cursus nunc, dc</p>
```

Moiton text after sth was removed: 
```
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. </p>
```

**Expected behavior**
~For Option A, step 4 should be prevented with the error message that changing the motion will result in inconsistencies with a change rec that should be resolved first.~

~For Option B, saving in step 5 should not be possible with an error message that says the motion has been edited and the reference for the change rec does not exist anymore.~

While editing the motion the warning text "Warning: Amendments exist for this motion. [...]" should be change to "Warning: Amendments or change recommendations exist for this motion. [...]" and this warning should be displayed if a motion has an amendment or a change recommendation  

And the change recommendation should be deletable even if the reference line is gone. 

The red text "Inconsistent data. A change recommendation or amendment is probably referring to a non-existant line number." is correctly displayed in some cases, but it should only be displayed once and only this line should be displayed directly where the change recom would be 

**Additional information:** 
Wanted behaviour already implemented: but the red line are too often there: 
Motion text: 
```
Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc,
```
Changed motion text:
```
Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo l
```

### PR DESCRIPTION
**Pull request by Elblinator**
closes #4679 
closes https://github.com/OpenSlides/openslides-client/pull/4782

### CODE REVIEW

**Comment by Elblinator** [comment]
After talking with @bastianjoel the following was decided:
- the test partical out of scope should return the last line 
- hence the function getChangeDiff(...) should ignore the changerecommendations completely if they are out of scope
- toChildTrace/fromChildTrace.length === = should throw errors -> everything else should act accordingly
- tests should be added for this toChildTrace/fromChildTrace case 
- accordingly should the check for currnode/ancestor be removed bc they won't be called if empty toChildTrace/fromChildTrace return errors
- checking if getError is necessary or can be removed or the like
-

**Comment by Elblinator** [comment]
adding the ```currNode``` and ```if(ancestor)``` extractRangeByLineNumbers(...) fixes [Amendment with all crossed out content: change reco not possible #5016](https://github.com/OpenSlides/openslides-client/issues/5016).
Should I readd these things and add tests here or should this be dealt with in another PR? @bastianjoel 


Additionally I tested [Amendments: Change recommandation can't be edited #5051](https://github.com/OpenSlides/openslides-client/issues/5051) and now the issue is different
==> if you add a change recommendation to a amendment then the thing is just broken and is not displayed at all. 
Screenshot_20250703_094937
I will look into it

**Comment by bastianjoel** [comment]
> Should I add these things and add tests here or should this be dealt with in another PR? @bastianjoel

If these changes involve `motion-diff.service.ts` and were not dicussed do it in another PR. There are already enough conceptual changes to the diff service in this PR.

**Comment by Elblinator** [comment]
If you approve please add @bspekker as assignee and reviewer

**Comment by Elblinator** [comment]
Please look at the ngAfterViewInit motion-detail-diff
I am not sure if this solution is really clean or should be changed

File: client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-detail-diff/motion-detail-diff.component.ts [hunk 1]
```diff
@@ -177,8 +187,8 @@ export class MotionDetailDiffComponent extends BaseMeetingComponent implements A
     public getTextBetweenChanges(change1: ViewUnifiedChange, change2: ViewUnifiedChange): string {
         // @TODO Highlighting
         const lineRange: LineRange = {
-            from: change1 ? change1.getLineTo() + 1 : (this.lineRange?.from ?? this.motion.firstLine),
-            to: change2 ? change2.getLineFrom() - 1 : (this.lineRange?.to ?? null)
+            to: change2 ? ((this.motion.isAmendment() || change2.getLineFrom() <= this.lastLineNr) ? change2.getLineFrom() - 1 : this.lastLineNr - 1) : (this.lineRange?.to ?? null),
+            from: change1 ? change1.getLineTo() + 1 : (this.lineRange?.from ?? this.motion.firstLine)
```
[the remark this answers is not in the document]
Comment (bastianjoel) [reply client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-detail-diff/motion-detail-diff.component.ts:191]: IMHO this is also too much logic within `... ? ... : ...` expressions.

File: client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-detail-diff/motion-detail-diff.component.ts [hunk 2]
```diff
@@ -350,14 +373,33 @@ export class MotionDetailDiffComponent extends BaseMeetingComponent implements A
             );
         };
 
-        this._allTextChangingObjects = this.changes.filter(
-            (obj: ViewUnifiedChange) => !obj.isTitleChange() && inRange(obj.getLineFrom(), obj.getLineTo())
+        this._workingTextChangingObjects = this.changes.filter(
+            (obj: ViewUnifiedChange) => !obj.isTitleChange() && inRange(obj.getLineFrom(), obj.getLineTo()) && (this.motion?.isAmendment() || (obj.getLineFrom() <= this.lastLineNr && obj.getLineTo() <= this.lastLineNr))
```
Comment (bastianjoel) [inline client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-detail-diff/motion-detail-diff.component.ts:377]: Why is this handled differently for amendments?

File: client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-detail-diff/motion-detail-diff.component.ts [hunk 3]
```diff
@@ -350,14 +373,33 @@ export class MotionDetailDiffComponent extends BaseMeetingComponent implements A
...
         );
+
+        this._brokenTextChangingObjects = this.changes.filter(
+            (obj: ViewUnifiedChange) => !obj.isTitleChange() && inRange(obj.getLineFrom(), obj.getLineTo()) && !this.motion?.isAmendment() && (obj.getLineFrom() > this.lastLineNr || obj.getLineTo() > this.lastLineNr)
+        );
+    }
+
+    private setLastNumber(): void {
```
Comment (bastianjoel) [inline client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-detail-diff/motion-detail-diff.component.ts:385]: `private` methods should be below `public` methods.

File: client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf.service/motion-pdf.service.ts [hunk 4]
```diff
@@ -672,7 +672,15 @@ export class MotionPdfService {
...
             const changes = this.motionFormatService.getUnifiedChanges(motion, lineLength);
-            const textChanges = changes.filter(change => !change.isTitleChange());
+            const baseText = this.lineNumberingService.insertLineNumbers({
+                html: motion!.text,
+                lineLength: lineLength,
+                firstLine: motion.firstLine
+            });
+            const lastLineNr = this.lineNumberingService.getLineNumberRange(baseText).to;
+            const workingTextChanges = changes.filter(change => !change.isTitleChange() && change.getLineFrom() <= lastLineNr && change.getLineTo() <= lastLineNr);
+            const brokenTextChangesAmount = changes.filter(change => !change.isTitleChange() && !motion.isAmendment() && (change.getLineFrom() > lastLineNr || change.getLineTo() > lastLineNr)).length;
```
Comment (bastianjoel) [inline client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf.service/motion-pdf.service.ts:682]: Isn't this just `changes.length - workingTextChanges.length`?

Comment (Elblinator) [reply client/src/app/site/pages/meetings/pages/motions/services/export/motion-pdf.service/motion-pdf.service.ts:682]: yes...

File: client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/motion-diff.service/motion-diff.service.ts [hunk 5]
```diff
@@ -2187,48 +2187,40 @@ export class MotionDiffService {
...
-                this.translate.instant(
-                    `A change recommendation or amendment is probably referring to a nonexistent line number.`
-                );
-            return `<em style="color: red; font-weight: bold;">` + msg + `</em>`;
+        changes.forEach((change: ViewUnifiedChange) => {
+            if (change.getLineTo() > maxFromLine && change.getLineTo() <= maxToLine) {
+                maxFromLine = change.getLineTo();
+                hasRemainederOneChangedLine = true;
+            }
+        }, 0);
```
[the remark this answers is not in the document]
Comment (bastianjoel) [reply client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/motion-diff.service/motion-diff.service.ts:2203]: No, I mean the `0` parameter used in `forEach`. From the docs this parameter is used to pass a `this` argument.

File: client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-detail-diff/motion-detail-diff.component.ts (hunk 2 above)
Comment (Elblinator) [reply client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-detail-diff/motion-detail-diff.component.ts:377]: Amendments need to be handled differently bc otherwise this bug appears:
>Additionally I tested [Amendments: Change recommandation can't be edited #5051](https://github.com/OpenSlides/openslides-client/issues/5051) and now the issue is different
==> if you add a change recommendation to a amendment then the thing is just broken and is not displayed at all. 
>

File: client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-detail-diff/motion-detail-diff.component.ts [hunk 6]
```diff
@@ -82,9 +82,17 @@ export class MotionDetailDiffComponent extends BaseMeetingComponent implements A
...
     @Input()
     public set changes(changes: ViewUnifiedChange[]) {
+        for (const change of changes) {
+            if (change.getLineFrom() <= this.lastLineNr && change.getLineTo() <= this.lastLineNr) {
+                this._changes.push(change);
+            } else {
+                this._brokenChanges.push(change);
+            }
+        }
         this._changes = changes || [];
```
[the remark this answers is not in the document]
Comment (Elblinator) [reply client/src/app/site/pages/meetings/pages/motions/pages/motion-detail/pages/motion-view/components/motion-detail-diff/motion-detail-diff.component.ts:96]: everything from this._brokenChanges is not needed

File: client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/line-numbering.service/line-numbering.service.ts [hunk 7]
```diff
@@ -825,6 +825,10 @@ export class LineNumberingService {
         let newHtml: string;
         let newRoot: Element;
 
+        if (html === undefined) {
+            html = ``;
+        }
+
```
[the remark this answers is not in the document]
Comment (Elblinator) [reply client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/line-numbering.service/line-numbering.service.ts]: removed bc it's not called in a broken state in this lastest version

File: client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/motion-diff.service/motion-diff.service.ts [hunk 8]
```diff
@@ -795,10 +801,16 @@ export class MotionDiffService {
         let followingHtmlStartSnippet = ``;
 
         fromChildTraceAbs.shift();
-        const previousHtml = this.serializePartialDomToChild(fragment, fromChildTraceAbs, false);
+        let previousHtml = ``;
+        if (fromChildTraceAbs.length > 0) {
+            previousHtml = this.serializePartialDomToChild(fragment, fromChildTraceAbs, false);
+        }
```
Comment (bastianjoel) [inline client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/motion-diff.service/motion-diff.service.ts:807]:
```suggestion
        let previousHtml = this.serializePartialDomToChild(fragment, fromChildTraceAbs, false);
```
Not needed anymore.

File: client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/motion-diff.service/motion-diff.service.ts [hunk 9]
```diff
@@ -795,10 +801,16 @@ export class MotionDiffService {
...
 
         toChildTraceAbs.shift();
-        const followingHtml = this.serializePartialDomFromChild(fragment, toChildTraceAbs, false);
+        let followingHtml = ``;
+        if (toChildTraceAbs.length > 0) {
+            followingHtml = this.serializePartialDomFromChild(fragment, toChildTraceAbs, false);
+        }
```
Comment (bastianjoel) [inline client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/motion-diff.service/motion-diff.service.ts:813]:
```suggestion
        let followingHtml = this.serializePartialDomFromChild(fragment, toChildTraceAbs, false);
```

File: client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/motion-diff.service/motion-diff.service.ts [hunk 10]
```diff
@@ -884,11 +896,15 @@ export class MotionDiffService {
             if (ancestor.childNodes[i] === fromChildTraceRel[0]) {
                 found = true;
                 fromChildTraceRel.shift();
-                htmlOut += this.serializePartialDomFromChild(ancestor.childNodes[i], fromChildTraceRel, true);
+                if (fromChildTraceRel.length > 0) {
+                    htmlOut += this.serializePartialDomFromChild(ancestor.childNodes[i], fromChildTraceRel, true);
+                }
```
Comment (bastianjoel) [inline client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/motion-diff.service/motion-diff.service.ts:901]:
```suggestion
                htmlOut += this.serializePartialDomFromChild(ancestor.childNodes[i], fromChildTraceRel, true);
```

File: client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/motion-diff.service/motion-diff.service.ts [hunk 11]
```diff
@@ -884,11 +896,15 @@ export class MotionDiffService {
...
             } else if (ancestor.childNodes[i] === toChildTraceRel[0]) {
                 found = false;
                 toChildTraceRel.shift();
-                htmlOut += this.serializePartialDomToChild(ancestor.childNodes[i], toChildTraceRel, true);
+                if (toChildTraceRel.length > 0) {
+                    htmlOut += this.serializePartialDomToChild(ancestor.childNodes[i], toChildTraceRel, true);
+                }
```
Comment (bastianjoel) [inline client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/motion-diff.service/motion-diff.service.ts:907]:
```suggestion
                htmlOut += this.serializePartialDomToChild(ancestor.childNodes[i], toChildTraceRel, true);
```

**Review by bastianjoel — CHANGES_REQUESTED** [review]

**Review by bastianjoel — APPROVED** [review]

**Review by bspekker — CHANGES_REQUESTED** [review]
One problem with change recommendations to deleted text: The remaining text before inconsistent CRs appears twice, cf. motions 3 and 4 in the test database.

File: client/src/app/site/pages/meetings/pages/motions/services/common/motion-format.service/motion-format.service.ts [hunk 12]
```diff
@@ -262,7 +262,7 @@ export class MotionFormatService {
         }
 
         text.push(
-            this.diffService.getTextRemainderAfterLastChange(motionText, changesToShow, lineLength, highlightedLine)
+            this.diffService.getTextRemainderAfterLastChange(motionText, changesToShow, brokenTextChangesAmount, lineLength, highlightedLine)
```
Comment (bastianjoel) [inline client/src/app/site/pages/meetings/pages/motions/services/common/motion-format.service/motion-format.service.ts:265]: Don't pass this value down.

**Review by bastianjoel — CHANGES_REQUESTED** [review]

File: client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/motion-diff.service/motion-diff.service.ts [hunk 13]
```diff
@@ -2172,11 +2172,11 @@ export class MotionDiffService {
         motionHtml: LineNumberedString,
         changes: ViewUnifiedChange[],
         lineLength: number,
-        brokenTextAmount: number,
         highlight?: number,
         lineRange?: LineRange
     ): string {
-        if (changes.length === 0 && brokenTextAmount === 0 && !lineRange) {
+        // if nothing was changed atthe motion
```
Comment (bastianjoel) [inline client/src/app/site/pages/meetings/pages/motions/modules/change-recommendations/services/motion-diff.service/motion-diff.service.ts:2178]:
```suggestion
```

**Review by bspekker — APPROVED** [review]
